export default {
  createGroup: null,
  groupDetails: null,
  groupsList: null,
  searchStaff: null,
  addStaffToGroup: null,
  groupStaffList: null,
  searchProgram: null,
  addProgramToGroup: null,
  groupProgramsList: null,
  searchProvider: null,
  addProviderToGroup: null,
  groupProvidersList: null,
  addGroupPermissions: null,
  groupPermissionsModules: null,
  groupPermissions: null,
  counter:0,
  errorMsg:null,
  dropdownList:null,
}