export default {
  createGroup: null,
  updateGroup: null,
  searchStaff: null,
  searchProgram: null,
  searchProvider: null,
  groupsList: null,
  groupDetails: null,
  addStaffToGroup: null,
  addProgramToGroup: null,
  addProviderToGroup: null,
  groupStaffList: null,
  groupProgramsList: null,
  groupProvidersList: null,
}