export default {
    counter:0,
    globalCodes:{},
    gender:null,
    language:null,
    country:null,
    state:null,
    pmOfcontact:null,
    ptOfDayContact:null,
    relation:null,
    demographics:null,
    healthCondition:null,
    patientReferals:null,
    patientPhysician:null,
    designations:null,
    programList:null,
    addProgram:null,
    deviceType:null,
    program:null,
    addDevice:null,
    successMsg:null, 
    errorMsg:null,
    patientList:null,
    column:null

}