export default {
    gender:null,
    language:null,
    country:null,
    state:null,
    pmOfcontact:null,
    ptOfDayContact:null,
    healthCondition:null,
    relation:null,
    designations:null,
    programList:null,
    deviceType:null,
    program:null,
    timeline:null,
    taskPriority:null,
    network:null,
    specialization:null,
    taskCategory:null,
    successMsg:null, 
    insuranceName:null,
    insuranceType:null,
    documentTags:null,
    documentTypes:null,
    loadingStatus:false,
    duration:null,
    typeOfVisit:null,
    staffList:null,
    noteTypes:null,
    noteCategories:null,
    programCategories:null,
    vitalFieldsList:null,
    vitalFieldsByDeviceId:null,
    frequencyTypes:null,
    modules:null,
    allPatientsList:null,
    allStaffList:null,
   



}