name: Virtare Care Frontend Pipeline
on:
  push:
    branches: [ V2 ]
  pull_request:
    branches: [ V2 ]
jobs:
  build:
    runs-on: [self-hosted, V2]
    strategy:
      matrix:
        node-version: [10.19.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build